# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lerobot.remote_inference import remote_policy_pb2 as lerobot_dot_remote__inference_dot_remote__policy__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lerobot/remote_inference/remote_policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemotePolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/lerobot.remote_inference.v1.RemotePolicyService/GetServerInfo',
                request_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.ServerInfo.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/lerobot.remote_inference.v1.RemotePolicyService/OpenSession',
                request_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/lerobot.remote_inference.v1.RemotePolicyService/Infer',
                request_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.InferRequest.SerializeToString,
                response_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.ActionChunk.FromString,
                _registered_method=True)
        self.ResetSession = channel.unary_unary(
                '/lerobot.remote_inference.v1.RemotePolicyService/ResetSession',
                request_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.SerializeToString,
                response_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/lerobot.remote_inference.v1.RemotePolicyService/CloseSession',
                request_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.SerializeToString,
                response_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.FromString,
                _registered_method=True)


class RemotePolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemotePolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.FromString,
                    response_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.ServerInfo.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionRequest.FromString,
                    response_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.InferRequest.FromString,
                    response_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.ActionChunk.SerializeToString,
            ),
            'ResetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSession,
                    request_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.FromString,
                    response_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.FromString,
                    response_serializer=lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot.remote_inference.v1.RemotePolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot.remote_inference.v1.RemotePolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemotePolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.remote_inference.v1.RemotePolicyService/GetServerInfo',
            lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.SerializeToString,
            lerobot_dot_remote__inference_dot_remote__policy__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.remote_inference.v1.RemotePolicyService/OpenSession',
            lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionRequest.SerializeToString,
            lerobot_dot_remote__inference_dot_remote__policy__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.remote_inference.v1.RemotePolicyService/Infer',
            lerobot_dot_remote__inference_dot_remote__policy__pb2.InferRequest.SerializeToString,
            lerobot_dot_remote__inference_dot_remote__policy__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.remote_inference.v1.RemotePolicyService/ResetSession',
            lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.SerializeToString,
            lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot.remote_inference.v1.RemotePolicyService/CloseSession',
            lerobot_dot_remote__inference_dot_remote__policy__pb2.SessionRequest.SerializeToString,
            lerobot_dot_remote__inference_dot_remote__policy__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
